# CMPU-395 Machine Learning Final Project

## I. GET FAMILIARIZED WITH PYTORCH (20% POINTS)

## What is Pytorch?

Pytorch allows an alternative to numpy in order to use the GPU rather than the CPU

Tensors are similar to ndarrays

In [1]:
from __future__ import print_function

In [2]:
import torch

* Unititialized 5x3 matrix

### Creation / Assignment

In [3]:
a = torch.empty(5,3)

In [4]:
print(a)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  2.4652e-32,  1.4013e-45],
        [ 2.4839e-32,  1.4013e-45,  2.4839e-32],
        [ 1.4013e-45,  2.4859e-32,  1.4013e-45],
        [ 2.4839e-32,  1.4013e-45,  2.4860e-32]])


In [9]:
b = torch.empty(5,3)
print(b)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -3.9274e-38]])


* Randomly initialized 5x3 matrix

In [6]:
y = torch.rand(5,3)

In [7]:
print(y)

tensor([[0.9459, 0.8519, 0.2081],
        [0.7483, 0.3266, 0.8548],
        [0.3570, 0.8204, 0.8502],
        [0.8731, 0.9361, 0.8724],
        [0.1433, 0.7251, 0.9397]])


In [8]:
z = torch.rand(5,3)
print(z)

tensor([[0.6180, 0.5870, 0.7458],
        [0.6119, 0.7583, 0.2163],
        [0.0514, 0.9792, 0.6780],
        [0.7788, 0.7550, 0.9090],
        [0.3766, 0.1305, 0.3744]])


Different because randomly initiialized

* Matrix filled with 0's of datatype long

In [11]:
ze = torch.zeros(5,3, dtype = torch.long)
print(ze)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


* Tensor with given data

In [13]:
d = torch.tensor([1.11, 2.22])
print(d)

tensor([1.1100, 2.2200])


* override created tensor datatype

In [19]:
d = d.new_ones(5,3, dtype = torch.double)
# or recreate -> d = torch.ones(5,3, dtype = torch.double)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [23]:
d = torch.rand_like(d, dtype= torch.float)
#converting d into random values
print(d)

tensor([[0.5724, 0.4641, 0.4806],
        [0.6266, 0.8857, 0.6423],
        [0.2241, 0.4857, 0.0311],
        [0.6020, 0.8970, 0.9590],
        [0.9430, 0.4257, 0.8822]])


* Show size of tensor

In [27]:
print(d.size())

torch.Size([5, 3])


<i>Size() supports all supple operations</i>

### Opperations

In [36]:
x = torch.rand(5,3)
y = torch.rand(5,3)

In [37]:
print(x + y)

tensor([[0.7449, 0.5094, 1.2860],
        [0.9017, 1.2214, 0.5404],
        [1.2650, 0.2798, 1.4547],
        [1.2937, 0.9850, 0.3616],
        [0.8746, 0.6320, 1.1162]])


or

In [38]:
print(torch.add(x,y))

tensor([[0.7449, 0.5094, 1.2860],
        [0.9017, 1.2214, 0.5404],
        [1.2650, 0.2798, 1.4547],
        [1.2937, 0.9850, 0.3616],
        [0.8746, 0.6320, 1.1162]])


*same result*

* Adding an output tensor

In [39]:
final = torch.empty(5,3)
torch.add(x,y, out = final)
print(final)

tensor([[0.7449, 0.5094, 1.2860],
        [0.9017, 1.2214, 0.5404],
        [1.2650, 0.2798, 1.4547],
        [1.2937, 0.9850, 0.3616],
        [0.8746, 0.6320, 1.1162]])


* Addition to one of the current tensors

In [41]:
y.add_(x)
print(y)

tensor([[0.7449, 0.5094, 1.2860],
        [0.9017, 1.2214, 0.5404],
        [1.2650, 0.2798, 1.4547],
        [1.2937, 0.9850, 0.3616],
        [0.8746, 0.6320, 1.1162]])


<i>All in place tensor mutation commands are followed with '_' </i>

* Numpy indexing

In [45]:
print(y[:,1]) #prints complete rows, second column

tensor([0.5094, 1.2214, 0.2798, 0.9850, 0.6320])


* torch.view used for resizing/ reshaping

In [55]:
a = torch.randn(4,4); print(a.size())
b = a.view(16); print(b.size()) 
c = a.view(-1, 8); print(c.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


* one element item

In [57]:
one = torch.rand(1)
print(one)
print(one.item())

tensor([0.0206])
0.02060699462890625


### Numpy <-> Torch

##### Torch -> Numpy

In [59]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [60]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [62]:
a.add_(2)
print(a)
print(b)
# Changes both!

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


#### Numpy -> Torch

In [63]:
import numpy as np

In [68]:
a = np.ones(5); print(a)
b = torch.from_numpy(a); print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [69]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


* Cuda conversion

In [72]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
    # No output, cuda is not available

## Autograd: Automatic Differentiation

* Autograd package - provides differenciation on all tensor.  
* requires_grad = True -> begins to track all operations on Tensor  
    * Can then call .grad or .backward() with these computations  
    * To stop tracking call .detach()  
* Function- .grad_fn references a function. 
* To computer derivative call .backward()
    

In [103]:
import torch

In [104]:
#create tensor with requires_grad = True
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [105]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


Because y was created as a result of an operation, it has a grad_fn

In [106]:
print(y.grad_fn)

More operations

In [107]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


requires gradient is initally set to false by default

In [108]:
a = torch.randn(2,2)
a = ((a * a) / (a * 3))
print(a.requires_grad)

False


In [109]:
a.requires_grad = True
print(a.requires_grad)

True


In [110]:
b = (a*a).sum()
print(b)
print(b.grad_fn)

tensor(0.5705, grad_fn=<SumBackward0>)


In [111]:
out.backward()


In [112]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [120]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)    

tensor([-1166.1617,  -560.1580,  -189.6617], grad_fn=<MulBackward0>)


In [121]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradients)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


using torch.no_grad to stop gradient tracking

In [126]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


## Neural Networks

* Can be constructed using the torch.nn package
* Feed forward network
    * Takes input, feeds through several layers, returns output    

#### Training Procedure for Neural Network
* Define NN that has some learnable parameters/weights
* Iterate over dataset of inputs
* Process this input through the network
* Compute the loss. The accuracy level / how far this network was from being correct
* Propogate gradients back into the networks weights
* Update the weights of the network
    * Do so through rule like: weight = weight - Learning Rate * gradient

#### Define Network

In [127]:
import torch
import torch.nn as nn 
import torch.nn.functional as F

In [128]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        # y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        #max pooling over a 2x2 window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # if size is a square
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


* The backward function is automatically defined using autograd

Parameters can be shown by net.parameters()

In [146]:
params = list(net.parameters())
print(len(params))
print(params[0].size()) #Weight of conv1

10
torch.Size([6, 1, 5, 5])


In [147]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0486,  0.0489,  0.0507,  0.0749, -0.0144,  0.0692,  0.0407,  0.1365,
          0.0422, -0.1130]], grad_fn=<AddmmBackward>)


In [148]:
net.zero_grad()
out.backward(torch.randn(1, 10))
print(out)

tensor([[ 0.0486,  0.0489,  0.0507,  0.0749, -0.0144,  0.0692,  0.0407,  0.1365,
          0.0422, -0.1130]], grad_fn=<AddmmBackward>)


##### Recap NN
* Torch.tensor()-> multi dimensional array with support for backward() and other autograd procedures
* nn.Module -> Neural Network module, convenient for encapsulating parameters
* nn.Parameter -> type of tensor automatically assigned as paramter when assigned to module
* autograd.Function -> implements forwards and backwards operations of autograd. 

#### Loss

Loss function takes in the output and target and tells how far the current algorithm is from the target


#### Mean Squared Loss -> nn.MSELoss

In [149]:
output = net(input)
target = torch.randn(10) #random target of same size
target = target.view(1,-1) # make same shape as input
criterion = nn.MSELoss()
loss = criterion(output,target)
print(loss)

tensor(0.9254, grad_fn=<MseLossBackward>)


In [152]:
print(loss.grad_fn) #MSELoss

In [153]:
print(loss.grad_fn.next_functions[0][0]) #Linear

In [154]:
print(loss.grad_fn.next_functions[0][0].next_functions[0][0]) #ReLu

* loss.backward()

In [155]:
net.zero_grad()

In [156]:
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])


In [157]:
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad after backward
tensor([-1.2571e-02, -9.2758e-05,  1.9786e-02, -5.2964e-03, -3.2564e-03,
         3.4207e-03])


#### Updating The Weights

* Stochastic Gradient Descent (SGD)
    * weight = weight - learningRate * gradient

In [159]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [161]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr = 0.01)

In [162]:
optimizer.zero_grad()
output = net(input)
loss = criterion(output,target)
loss.backward()
optimizer.step() #update

# Tutorial #2

* N Dimensional Tensore
* Automatic differentiation

<b>First Implement network using numpy</b>

In [1]:
import numpy as np

In [2]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension

In [3]:
N, D_in, H, D_out = 64, 1000, 100, 10

In [5]:
# random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

In [6]:
# randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

In [7]:
learning_rate = 1e-6

In [12]:
for t in range(500):
    #forward pass, compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    #compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    #compute gradients of weights with loss. BackPropegation
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)
    #update Weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 31318067.3026
1 28020490.5301
2 27253592.4132
3 25122891.4841
4 20479913.4506
5 14341554.1164
6 8912405.70557
7 5202626.99947
8 3068468.63539
9 1916633.16616
10 1299466.08922
11 952350.134729
12 741359.690366
13 601082.324476
14 500402.412898
15 423752.055742
16 363028.573876
17 313573.543233
18 272576.636828
19 238225.915417
20 209254.70009
21 184551.473595
22 163346.577876
23 145047.948036
24 129179.291567
25 115361.128548
26 103295.944095
27 92711.2767448
28 83399.2129047
29 75184.3683487
30 67923.5585768
31 61488.4894719
32 55768.6694321
33 50667.445748
34 46110.47318
35 42030.0370527
36 38369.4760461
37 35074.2112586
38 32105.1770209
39 29428.3998026
40 27009.0589971
41 24820.1928709
42 22834.1493674
43 21030.8681395
44 19396.6617729
45 17911.95538
46 16556.5441703
47 15318.9448346
48 14188.0042849
49 13152.5098265
50 12203.6513827
51 11333.24617
52 10533.9237761
53 9799.12841028
54 9123.20120484
55 8500.15487325
56 7926.05414527
57 7396.33631231
58 6906.92959016
59 6455.8840679

<b> Now Using PyTorch </b>

In [14]:
import torch

In [15]:
dtype = torch.float
device = torch.device("cpu")

In [16]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension

In [17]:
N, D_in, H, D_out = 64, 1000, 100, 10

In [18]:
#random input and output data
x = torch.randn(N, D_in, device = device, dtype = dtype)
y = torch.randn(N, D_out, device = device, dtype = dtype)

In [20]:
# initialize weights
w1 = torch.randn(D_in, H, device = device, dtype = dtype)
w2 = torch.randn(H, D_out, device = device, dtype = dtype)

In [22]:
learning_rate = 1e-6

In [26]:
for t in range(500):
    # forward pass, predict y
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)
    
    #compute loss
    loss = (y_pred - y).pow(2).sum().item()
    print(t, loss)
    
    # Backprop to compute gradients and loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h<0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    # update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 32890718.0
1 36453556.0
2 50678720.0
3 65398416.0
4 60690328.0
5 33411508.0
6 10773404.0
7 3272886.5
8 1616204.0
9 1161857.625
10 941498.8125
11 787701.8125
12 667005.6875
13 569065.875
14 488381.46875
15 421339.6875
16 365223.90625
17 317921.59375
18 277773.5
19 243493.8125
20 214106.96875
21 188830.0
22 166987.828125
23 148048.421875
24 131553.265625
25 117153.484375
26 104538.5
27 93472.0625
28 83728.6796875
29 75130.734375
30 67534.625
31 60799.71484375
32 54817.3203125
33 49492.203125
34 44745.69921875
35 40507.39453125
36 36718.53125
37 33324.1796875
38 30279.66796875
39 27543.9609375
40 25082.927734375
41 22873.412109375
42 20880.810546875
43 19080.97265625
44 17451.998046875
45 15979.6025390625
46 14645.15234375
47 13434.87109375
48 12336.15234375
49 11336.9169921875
50 10427.458984375
51 9598.9306640625
52 8843.7646484375
53 8154.421875
54 7524.408203125
55 6948.208984375
56 6420.96728515625
57 5937.681640625
58 5494.66845703125
59 5088.11279296875
60 4714.68408203125
61 437

456 0.0003583927755244076
457 0.0003504652122501284
458 0.00034382447483949363
459 0.00033698001061566174
460 0.00033042303402908146
461 0.0003238182980567217
462 0.00031752994982525706
463 0.0003111752448603511
464 0.0003049128863494843
465 0.0002984526799991727
466 0.0002932169009000063
467 0.0002876455255318433
468 0.00028188221040181816
469 0.0002763430238701403
470 0.000271470082225278
471 0.0002661901817191392
472 0.0002615738776512444
473 0.00025714075309224427
474 0.0002522874856367707
475 0.0002477757807355374
476 0.00024320765805896372
477 0.00023892780882306397
478 0.0002342646912438795
479 0.0002303691435372457
480 0.0002259495813632384
481 0.00022280232224147767
482 0.00021877026301808655
483 0.000215012434637174
484 0.00021141859178896993
485 0.00020784606749657542
486 0.00020386773394420743
487 0.0002003420959226787
488 0.0001973316539078951
489 0.00019411671382840723
490 0.00019059976330026984
491 0.00018750876188278198
492 0.0001845807273639366
493 0.000181236668140627

<b> Tensors and Autograd </b>

In [37]:
import torch

In [38]:
dtype = torch.float
device = torch.device("cpu")

In [39]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10

In [40]:
x = torch.randn(N, D_in, device = device, dtype = dtype)
y = torch.randn(N, D_out, device = device, dtype = dtype)

In [47]:
w1 = torch.randn(D_in, H, device = device, dtype = dtype, requires_grad = True)
w2 = torch.randn(H, D_out, device = device, dtype = dtype, requires_grad = True)

In [48]:
learning_rate = 1e-6

In [50]:
for t in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()

0 5.185095142223872e-05
1 5.130972567712888e-05
2 5.088702164357528e-05
3 5.0295489927520975e-05
4 4.95427921123337e-05
5 4.911394353257492e-05
6 4.858049942413345e-05
7 4.781587267643772e-05
8 4.729269858216867e-05
9 4.7044475650181994e-05
10 4.630845069186762e-05
11 4.570570308715105e-05
12 4.5123491872800514e-05
13 4.468164115678519e-05
14 4.426515806699172e-05
15 4.3880394514417276e-05
16 4.3273383198538795e-05
17 4.2802319512702525e-05
18 4.245289892423898e-05
19 4.2165822378592566e-05
20 4.157700823270716e-05
21 4.1183266148436815e-05
22 4.07181832997594e-05
23 4.028841794934124e-05
24 4.005789742222987e-05
25 3.944393392885104e-05
26 3.894627661793493e-05
27 3.8528542063431814e-05
28 3.828787521342747e-05
29 3.7949397665215656e-05
30 3.7313489883672446e-05
31 3.704108530655503e-05
32 3.6640045436797664e-05
33 3.6314158933237195e-05
34 3.600864511099644e-05
35 3.5707085771718994e-05
36 3.5180841223336756e-05
37 3.5019602364627644e-05
38 3.469004877842963e-05
39 3.4278742532478645

352 7.134232873795554e-06
353 7.1300692070508376e-06
354 7.120710506569594e-06
355 7.087434369168477e-06
356 7.029578227957245e-06
357 7.035555427137297e-06
358 7.006897249084432e-06
359 7.010623448877595e-06
360 6.998429398663575e-06
361 6.920482064742828e-06
362 6.9173152041912545e-06
363 6.908637260494288e-06
364 6.867723641335033e-06
365 6.852738351881271e-06
366 6.831220161984675e-06
367 6.825301170465536e-06
368 6.787992788304109e-06
369 6.75171440889244e-06
370 6.711840796924662e-06
371 6.719455086567905e-06
372 6.69144856146886e-06
373 6.637598289671587e-06
374 6.63375249132514e-06
375 6.626069989579264e-06
376 6.569065590156242e-06
377 6.589566510228906e-06
378 6.571381618414307e-06
379 6.520271199406125e-06
380 6.509053491754457e-06
381 6.507543730549514e-06
382 6.500171366496943e-06
383 6.469711024692515e-06
384 6.451898116210941e-06
385 6.459117685153615e-06
386 6.454337835748447e-06
387 6.431663678085897e-06
388 6.425763785955496e-06
389 6.40972984911059e-06
390 6.39746212

<b> New Autograd Functions</b>

In [51]:
import torch

In [52]:
class MyReLU(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)
    
    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input
    

In [53]:
dtype = torch.float
device = torch.device("cpu")
    
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10
        

In [54]:
x = torch.randn(N, D_in, dtype = dtype, device = device)
y = torch.randn(N, D_out, dtype = dtype, device = device)

In [58]:
w1 = torch.randn(D_in, H, dtype = dtype, device = device, requires_grad = True)
w2 = torch.randn(H, D_out, dtype = dtype, device = device, requires_grad = True)

In [59]:
learning_rate = 1e-6

In [61]:
for t in range(500):
    relu = MyReLU.apply
    y_pred = relu(x.mm(w1)).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    print(t, loss)
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()

0 tensor(24935384., grad_fn=<SumBackward0>)
1 tensor(8365785., grad_fn=<SumBackward0>)
2 tensor(7445304., grad_fn=<SumBackward0>)
3 tensor(6604499.5000, grad_fn=<SumBackward0>)
4 tensor(5775269.5000, grad_fn=<SumBackward0>)
5 tensor(4950017.5000, grad_fn=<SumBackward0>)
6 tensor(4154605.7500, grad_fn=<SumBackward0>)
7 tensor(3420112.5000, grad_fn=<SumBackward0>)
8 tensor(2771786., grad_fn=<SumBackward0>)
9 tensor(2220768.2500, grad_fn=<SumBackward0>)
10 tensor(1768043.2500, grad_fn=<SumBackward0>)
11 tensor(1404286.2500, grad_fn=<SumBackward0>)
12 tensor(1117069.7500, grad_fn=<SumBackward0>)
13 tensor(892996.3750, grad_fn=<SumBackward0>)
14 tensor(718799.2500, grad_fn=<SumBackward0>)
15 tensor(583699.8125, grad_fn=<SumBackward0>)
16 tensor(478589.5625, grad_fn=<SumBackward0>)
17 tensor(396458.7188, grad_fn=<SumBackward0>)
18 tensor(331734.3125, grad_fn=<SumBackward0>)
19 tensor(280290.0312, grad_fn=<SumBackward0>)
20 tensor(238996.1719, grad_fn=<SumBackward0>)
21 tensor(205539.5000, gr

211 tensor(1.8269, grad_fn=<SumBackward0>)
212 tensor(1.7477, grad_fn=<SumBackward0>)
213 tensor(1.6720, grad_fn=<SumBackward0>)
214 tensor(1.5997, grad_fn=<SumBackward0>)
215 tensor(1.5307, grad_fn=<SumBackward0>)
216 tensor(1.4646, grad_fn=<SumBackward0>)
217 tensor(1.4017, grad_fn=<SumBackward0>)
218 tensor(1.3414, grad_fn=<SumBackward0>)
219 tensor(1.2837, grad_fn=<SumBackward0>)
220 tensor(1.2287, grad_fn=<SumBackward0>)
221 tensor(1.1760, grad_fn=<SumBackward0>)
222 tensor(1.1256, grad_fn=<SumBackward0>)
223 tensor(1.0776, grad_fn=<SumBackward0>)
224 tensor(1.0316, grad_fn=<SumBackward0>)
225 tensor(0.9875, grad_fn=<SumBackward0>)
226 tensor(0.9455, grad_fn=<SumBackward0>)
227 tensor(0.9052, grad_fn=<SumBackward0>)
228 tensor(0.8668, grad_fn=<SumBackward0>)
229 tensor(0.8300, grad_fn=<SumBackward0>)
230 tensor(0.7948, grad_fn=<SumBackward0>)
231 tensor(0.7611, grad_fn=<SumBackward0>)
232 tensor(0.7288, grad_fn=<SumBackward0>)
233 tensor(0.6980, grad_fn=<SumBackward0>)
234 tensor(

424 tensor(0.0005, grad_fn=<SumBackward0>)
425 tensor(0.0005, grad_fn=<SumBackward0>)
426 tensor(0.0005, grad_fn=<SumBackward0>)
427 tensor(0.0005, grad_fn=<SumBackward0>)
428 tensor(0.0005, grad_fn=<SumBackward0>)
429 tensor(0.0005, grad_fn=<SumBackward0>)
430 tensor(0.0005, grad_fn=<SumBackward0>)
431 tensor(0.0005, grad_fn=<SumBackward0>)
432 tensor(0.0004, grad_fn=<SumBackward0>)
433 tensor(0.0004, grad_fn=<SumBackward0>)
434 tensor(0.0004, grad_fn=<SumBackward0>)
435 tensor(0.0004, grad_fn=<SumBackward0>)
436 tensor(0.0004, grad_fn=<SumBackward0>)
437 tensor(0.0004, grad_fn=<SumBackward0>)
438 tensor(0.0004, grad_fn=<SumBackward0>)
439 tensor(0.0004, grad_fn=<SumBackward0>)
440 tensor(0.0004, grad_fn=<SumBackward0>)
441 tensor(0.0004, grad_fn=<SumBackward0>)
442 tensor(0.0003, grad_fn=<SumBackward0>)
443 tensor(0.0003, grad_fn=<SumBackward0>)
444 tensor(0.0003, grad_fn=<SumBackward0>)
445 tensor(0.0003, grad_fn=<SumBackward0>)
446 tensor(0.0003, grad_fn=<SumBackward0>)
447 tensor(

<b> TensorFlow: Static Graphs</b>

In [20]:
import tensorflow as tf
import torch
import numpy as np

In [9]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10

In [10]:
# Place holders for target files
x = tf.placeholder(tf.float32, shape = (None, D_in))
y = tf.placeholder(tf.float32, shape = (None, D_out))

In [12]:
#random weights
w1 = tf.Variable(tf.random_normal((D_in, H)))
w2 = tf.Variable(tf.random_normal((H, D_out)))

In [13]:
h = tf.matmul(x, w1)
h_relu = tf.maximum(h, tf.zeros(1))
y_pred = tf.matmul(h_relu, w2)

In [14]:
# Compute loss using operations on TensorFlow Tensors
loss = tf.reduce_sum((y - y_pred) ** 2.0)

In [17]:
# gradient of loss
grad_w1, grad_w2 = tf.gradients(loss, [w1, w2])

In [18]:
learning_rate = 1e-6
new_w1 = w1.assign(w1 - learning_rate * grad_w1)
new_w2 = w2.assign(w2 - learning_rate * grad_w2)

In [21]:
with tf.Session() as sess:
    # Run the graph once to initialize the Variables w1 and w2.
    sess.run(tf.global_variables_initializer())
    # Create numpy arrays holding the actual data for the inputs x and targets
    # y
    x_value = np.random.randn(N, D_in)
    y_value = np.random.randn(N, D_out)
    for _ in range(500):
        loss_value, _, _ = sess.run([loss, new_w1, new_w2],
                                    feed_dict={x: x_value, y: y_value})
        print(loss_value)

30597780.0
25971506.0
27546262.0
30963618.0
34770864.0
42525736.0
41060812.0
28591792.0
14011007.0
5558101.0
2264197.5
1163534.8
771715.3
598418.0
497429.34
425418.4
368548.78
321621.97
282157.5
248594.88
219857.38
195122.14
173739.03
155166.16
138966.0
124783.52
112327.08
101354.98
91664.77
83087.72
75469.87
68700.53
62663.906
57254.453
52397.734
48028.707
44090.055
40536.992
37321.656
34405.77
31757.977
29349.434
27155.99
25157.605
23331.396
21662.07
20132.426
18728.61
17439.023
16253.041
15160.822
14154.924
13226.539
12368.795
11575.783
10843.265
10164.814
9535.818
8951.862
8409.491
7905.1113
7435.8013
6999.4355
6592.702
6213.1504
5858.742
5527.673
5218.045
4928.494
4657.4814
4403.5938
4165.6367
3942.3193
3732.7217
3535.917
3350.984
3177.1274
3013.567
2859.5898
2714.601
2577.9822
2449.095
2327.5576
2212.8906
2104.6345
2002.4177
1905.8467
1814.5337
1728.1981
1646.487
1569.1335
1495.8796
1426.487
1360.7004
1298.3241
1239.1667
1183.0378
1129.7451
1079.1329
1031.0852
985.4105
941.9918
9

<b> Pytorch NN </b>

In [22]:
import torch

In [23]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10

In [24]:
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

In [25]:
# implement model using layers
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

In [26]:
loss_fn = torch.nn.MSELoss(reduction='sum')

In [28]:
learning_rate = 1e-4
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    print(t, loss.item())
    model.zero_grad()
    loss.backward()
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

0 761.9904174804688
1 707.7374877929688
2 661.0242309570312
3 619.4326171875
4 582.4786987304688
5 549.1841430664062
6 518.7296142578125
7 490.60595703125
8 464.744140625
9 440.4861755371094
10 417.4515380859375
11 395.7400207519531
12 375.21514892578125
13 355.6513671875
14 337.0811462402344
15 319.3311767578125
16 302.369873046875
17 286.1929626464844
18 270.7523193359375
19 256.0176696777344
20 241.9156494140625
21 228.46078491210938
22 215.66757202148438
23 203.49295043945312
24 191.85409545898438
25 180.783447265625
26 170.25491333007812
27 160.2572784423828
28 150.75369262695312
29 141.74600219726562
30 133.2347869873047
31 125.17642211914062
32 117.5662612915039
33 110.39634704589844
34 103.64672088623047
35 97.3051986694336
36 91.34839630126953
37 85.74333953857422
38 80.45897674560547
39 75.49961853027344
40 70.83850860595703
41 66.48493194580078
42 62.40781021118164
43 58.58635330200195
44 55.01475524902344
45 51.6721076965332
46 48.542964935302734
47 45.61442184448242
48 42.

359 0.00010435344302095473
360 0.00010083537927130237
361 9.744337876327336e-05
362 9.416456305189058e-05
363 9.099997259909287e-05
364 8.794401219347492e-05
365 8.499282557750121e-05
366 8.21421854197979e-05
367 7.938571070553735e-05
368 7.672442006878555e-05
369 7.415989239234477e-05
370 7.167732837842777e-05
371 6.928494258318096e-05
372 6.696872151223943e-05
373 6.473325629485771e-05
374 6.257177301449701e-05
375 6.048761497368105e-05
376 5.847289503435604e-05
377 5.65254595130682e-05
378 5.464362402562983e-05
379 5.282575875753537e-05
380 5.1070474000880495e-05
381 4.9375077651347965e-05
382 4.773613181896508e-05
383 4.615170109900646e-05
384 4.4622469431487843e-05
385 4.314338730182499e-05
386 4.171494583715685e-05
387 4.033674122183584e-05
388 3.900290539604612e-05
389 3.771137198782526e-05
390 3.646485129138455e-05
391 3.5263103200122714e-05
392 3.4100503398803994e-05
393 3.297638613730669e-05
394 3.188791743014008e-05
395 3.083862247876823e-05
396 2.98241175187286e-05
397 2.88

<b> PyTorch: optim </b>

In [29]:
import torch

In [30]:
# N -> Batch Size
# D_in -> Input dimension
# D_out -> output dimension
# H -> Hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10

In [31]:
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# implement model using layers
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

In [32]:
loss_fn = torch.nn.MSELoss(reduction='sum')

In [35]:
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 658.7882690429688
1 641.6917724609375
2 625.1233520507812
3 609.1522827148438
4 593.6106567382812
5 578.4814453125
6 563.7494506835938
7 549.4237060546875
8 535.4823608398438
9 521.9257202148438
10 508.7012023925781
11 495.850830078125
12 483.3809814453125
13 471.2648010253906
14 459.466796875
15 448.0201721191406
16 436.8922424316406
17 426.07171630859375
18 415.5414733886719
19 405.32647705078125
20 395.39031982421875
21 385.82025146484375
22 376.53680419921875
23 367.462890625
24 358.6536865234375
25 350.1427917480469
26 341.86669921875
27 333.8283996582031
28 325.9950256347656
29 318.3411865234375
30 310.8473815917969
31 303.5145263671875
32 296.3424072265625
33 289.322509765625
34 282.4693908691406
35 275.8055114746094
36 269.2689514160156
37 262.8716125488281
38 256.63519287109375
39 250.5413360595703
40 244.56858825683594
41 238.70277404785156
42 232.95184326171875
43 227.3152618408203
44 221.81163024902344
45 216.41893005371094
46 211.13363647460938
47 205.9539337158203
48 20

381 1.212974439113168e-05
382 1.1293231182207819e-05
383 1.0515108442632481e-05
384 9.790260264708195e-06
385 9.112744010053575e-06
386 8.48273339215666e-06
387 7.894663212937303e-06
388 7.347412974922918e-06
389 6.835320618847618e-06
390 6.359888175211381e-06
391 5.91702837482444e-06
392 5.504296495928429e-06
393 5.120023615745595e-06
394 4.762250682688318e-06
395 4.428827196534257e-06
396 4.11894643548294e-06
397 3.830627065326553e-06
398 3.5613377349363873e-06
399 3.3112714845628943e-06
400 3.0796709324931726e-06
401 2.8627841857087333e-06
402 2.6615284696163144e-06
403 2.4745606879150728e-06
404 2.3006020910543157e-06
405 2.138531272066757e-06
406 1.9877415979863144e-06
407 1.8483264057067572e-06
408 1.7176513438244e-06
409 1.5970280173860374e-06
410 1.4842245263935183e-06
411 1.380483126922627e-06
412 1.283355345549353e-06
413 1.1933639143535402e-06
414 1.109308072955173e-06
415 1.0315339977751137e-06
416 9.592272363079246e-07
417 8.918290745896229e-07
418 8.298092666336743e-07
41

<b> PyTorch: Custom nn Modules </b>

In [36]:
import torch

In [37]:
class TwoLayerNet(torch.nn.Module):
    
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)
        
    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred
    
N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
model = TwoLayerNet(D_in, H, D_out)

criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 659.6419067382812
1 614.3047485351562
2 574.6154174804688
3 539.3997802734375
4 507.59552001953125
5 478.80645751953125
6 452.31146240234375
7 427.7949523925781
8 405.141357421875
9 383.91705322265625
10 363.86895751953125
11 344.9630126953125
12 327.0054016113281
13 310.0469055175781
14 293.9658203125
15 278.7015075683594
16 264.1309814453125
17 250.20896911621094
18 236.97943115234375
19 224.366943359375
20 212.3256072998047
21 200.8095245361328
22 189.770751953125
23 179.30203247070312
24 169.32740783691406
25 159.79934692382812
26 150.75372314453125
27 142.160400390625
28 134.013427734375
29 126.29348754882812
30 118.98748779296875
31 112.0608901977539
32 105.52568054199219
33 99.34239959716797
34 93.49171447753906
35 87.97622680664062
36 82.78002166748047
37 77.90019989013672
38 73.30926513671875
39 68.98790740966797
40 64.9284896850586
41 61.1192626953125
42 57.53740692138672
43 54.168087005615234
44 51.006168365478516
45 48.034244537353516
46 45.236270904541016
47 42.609722137

369 0.0001588941231602803
370 0.0001544441911391914
371 0.00015012017684057355
372 0.00014592832303605974
373 0.00014184933388605714
374 0.00013789690274279565
375 0.0001340516027994454
376 0.00013032265997026116
377 0.0001267023617401719
378 0.00012318142398726195
379 0.00011976408859482035
380 0.00011644543701549992
381 0.00011322188220219687
382 0.000110089014924597
383 0.00010705086606321856
384 0.00010409386595711112
385 0.00010122179082827643
386 9.843453881330788e-05
387 9.572714770911261e-05
388 9.309287997893989e-05
389 9.053712710738182e-05
390 8.805223478702828e-05
391 8.564141171518713e-05
392 8.329607953783125e-05
393 8.10168421594426e-05
394 7.880283374106511e-05
395 7.664948498131707e-05
396 7.455603190464899e-05
397 7.252684008562937e-05
398 7.05485581420362e-05
399 6.863045564386994e-05
400 6.676591874565929e-05
401 6.49529101792723e-05
402 6.319021485978737e-05
403 6.14781747572124e-05
404 5.98128026467748e-05
405 5.819563739350997e-05
406 5.662049079546705e-05
407 5.

In [38]:
import random 
import torch

In [39]:
class DynamicNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(DynamicNet, self).__init__()
        self.input_linear = torch.nn.Linear(D_in, H)
        self.middle_linear = torch.nn.Linear(H, H)
        self.output_linear = torch.nn.Linear(H, D_out)
    def forward(self, x):
        h_relu = self.input_linear(x).clamp(min=0)
        for _ in range(random.randint(0, 3)):
            h_relu = self.middle_linear(h_relu).clamp(min=0)
        y_pred = self.output_linear(h_relu)
        return y_pred
N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
model = DynamicNet(D_in, H, D_out)
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


0 682.4524536132812
1 682.2467651367188
2 691.7889404296875
3 656.6134643554688
4 671.1824951171875
5 665.9881591796875
6 659.9257202148438
7 522.2828979492188
8 663.6219482421875
9 606.4755249023438
10 638.2224731445312
11 632.8020629882812
12 626.44921875
13 578.43359375
14 566.8640747070312
15 646.50244140625
16 642.9388427734375
17 339.07415771484375
18 503.7922058105469
19 628.9352416992188
20 563.4932861328125
21 246.5957794189453
22 603.9635620117188
23 196.2297821044922
24 391.2505187988281
25 492.9062194824219
26 353.26593017578125
27 453.8765563964844
28 131.3162078857422
29 289.48504638671875
30 265.17364501953125
31 458.40008544921875
32 434.7265625
33 105.13446807861328
34 97.38928985595703
35 78.8643569946289
36 171.141357421875
37 145.7572021484375
38 119.6600341796875
39 327.08160400390625
40 217.28936767578125
41 279.554443359375
42 106.21338653564453
43 288.3518371582031
44 203.3406219482422
45 100.11004638671875
46 122.77983856201172
47 95.01863861083984
48 76.967842

382 1.2370622158050537
383 0.7819073796272278
384 0.3158971667289734
385 0.5245500802993774
386 0.952060341835022
387 1.528668999671936
388 0.4974156618118286
389 0.8561351299285889
390 0.7728099822998047
391 1.2501721382141113
392 1.1738053560256958
393 1.115722894668579
394 0.9940949082374573
395 0.7067437171936035
396 0.7467183470726013
397 0.7438216805458069
398 0.6852268576622009
399 0.6060201525688171
400 1.0187517404556274
401 0.30655810236930847
402 0.5909096002578735
403 0.9810411930084229
404 0.4720135033130646
405 0.8784210085868835
406 0.8394002914428711
407 0.24588020145893097
408 0.6883680820465088
409 0.5879430174827576
410 0.7556260824203491
411 0.6505295038223267
412 0.8106364607810974
413 0.6039459109306335
414 0.26235440373420715
415 0.5395017862319946
416 0.2862224280834198
417 0.5456554293632507
418 0.4512519836425781
419 0.8877772092819214
420 0.27930474281311035
421 0.2451646327972412
422 0.436242938041687
423 0.7921857237815857
424 0.4409501850605011
425 0.11647